import Foundation
import AetherLibavcodec
import Testing
@testable import AetherEngine

/// #699 follow-up: the software host seeks to a resume position before its first read. The repair
/// verdict used to be reached at that first read, so it sampled the landing instead of the head, met
/// an open-GOP keyframe whose picture order is not 0, refused, and the session played in decode
/// order. A seek before the first read now settles the verdict at the head first.
@Suite("Composition-offset repair when the first move is a seek (#699)")
struct CompositionOffsetRepairFirstSeekTests {

    private struct Timestamps: Equatable, CustomStringConvertible {
        var pts: Int64
        var dts: Int64
        var description: String { "pts=\(pts) dts=\(dts)" }
    }

    /// Opens the fixture, seeks before reading anything (the resume shape), and returns the video
    /// timestamps from the landing on.
    private static func videoTimestamps(
        base64: String, seekingTo seconds: Double, afterReading readFirst: Int = 0
    ) throws -> [Timestamps] {
        let data = try #require(Data(base64Encoded: base64, options: .ignoreUnknownCharacters))
        let demuxer = Demuxer()
        try demuxer.open(reader: DataIOReader(data: data), formatHint: "mp4")
        defer { demuxer.close() }
        for _ in 0..<readFirst {
            var owned = try demuxer.readPacket()
            trackedPacketFree(&owned)
        }
        #expect(demuxer.seek(to: seconds))
        let videoIndex = demuxer.videoStreamIndex
        var result: [Timestamps] = []
        while let packet = try? demuxer.readPacket() {
            if packet.pointee.stream_index == videoIndex {
                result.append(Timestamps(pts: packet.pointee.pts, dts: packet.pointee.dts))
            }
            var owned: UnsafeMutablePointer<AVPacket>? = packet
            trackedPacketFree(&owned)
        }
        return result
    }

    @Test("a resume onto the CRA carries the healthy twin's timestamps")
    func resumeOntoCRAIsRepaired() throws {
        let healthy = try Self.videoTimestamps(base64: Self.healthyFixtureBase64, seekingTo: 0.6)
        let repaired = try Self.videoTimestamps(base64: Self.missingFixtureBase64, seekingTo: 0.6)
        // The landing is the CRA at 0.6 s (7680 ticks), decoded ahead of its leading pictures.
        #expect(healthy.first == Timestamps(pts: 7680, dts: 6144))
        #expect(healthy.contains { $0.pts != $0.dts })
        #expect(repaired == healthy)
    }

    /// The native path decides at the head and seeks later. Its landing used to be anchored as if
    /// the CRA were the first picture displayed, so the axis sat one slot early per leading picture.
    @Test("a seek after playback started counts the landing's leading pictures")
    func seekAfterReadingCountsLeadingPictures() throws {
        let healthy = try Self.videoTimestamps(base64: Self.healthyFixtureBase64, seekingTo: 0.6, afterReading: 8)
        let repaired = try Self.videoTimestamps(base64: Self.missingFixtureBase64, seekingTo: 0.6, afterReading: 8)
        #expect(healthy.first == Timestamps(pts: 7680, dts: 6144))
        #expect(repaired == healthy)
    }

    @Test("the healthy twin is untouched by the head sample a first seek now takes")
    func healthyTwinSurvivesTheHeadSample() throws {
        let fromHead = try Self.videoTimestamps(base64: Self.healthyFixtureBase64, seekingTo: 0)
        #expect(fromHead.count == 60)
        #expect(fromHead.first == Timestamps(pts: 0, dts: -512))
    }

    /// 64x64 HEVC Main 10, 50 fps, 60 frames, four B pictures per hierarchical mini-GOP, and an
    /// open-GOP CRA with leading pictures at frame 30.
    ///
    ///     ffmpeg -f lavfi -i 'testsrc=s=64x64:r=50:d=1.2' -frames:v 60 -c:v libx265 -preset ultrafast \
    ///       -pix_fmt yuv420p10le -x265-params \
    ///       'bframes=4:b-pyramid=1:b-adapt=0:keyint=30:min-keyint=30:scenecut=0:open-gop=1' \
    ///       -tag:v hvc1 -movflags +faststart healthy.mp4
    ///     ffmpeg -i healthy.mp4 -map 0:v:0 -c:v copy -bsf:v 'setts=pts=DTS' \
    ///       -movflags +faststart missing.mp4
    private static let healthyFixtureBase64 = """
        AAAAHGZ0eXBpc29tAAACAGlzb21pc28ybXA0MQAAD1htb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAAEsAABAAABAAAAAAAA
        AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAOgnRy
        YWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAEAAAAAAAAEsAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA
        AAAAAAAAAEAAAAAAQAAAAEAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAABLAAAAIAAAEAAAAADfptZGlhAAAAIG1kaGQAAAAA
        AAAAAAAAAAAAADIAAAA8AFXEAAAAAAAtaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAAAA2lbWluZgAA
        ABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAANZXN0YmwAAAoZc3RzZAAAAAAA
        AAABAAAKCWh2YzEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAQABAAEgAAABIAAAAAAAAAAEVTGF2YzYyLjI4LjEwMSBsaWJ4MjY1
        AAAAAAAAAAAAAAAY//8AAAmFaHZjQwECIAAAAJAAAAAAAB7wAPz9+voAAA8EoAABABhAAQwB//8CIAAAAwCQAAADAAADAB6VmAmh
        AAEAKkIBAQIgAAADAJAAAAMAAAMAHqAggQTZZWZKTC8BaAgAAAMACAAAAwGQQKIAAQAGRAHAc8CJJwABCQpOAQX///////////8F
        LKLeCbUXR9u7VaT+f8L8TngyNjUgKGJ1aWxkIDIxNikgLSA0LjIrMS1lNDQ0NzQ0OltNYWMgT1MgWF1bY2xhbmcgMjEuMC4wXVs2
        NCBiaXRdIDEwYml0IC0gSC4yNjUvSEVWQyBjb2RlYyAtIENvcHlyaWdodCAyMDEzLTIwMTggKGMpIE11bHRpY29yZXdhcmUsIElu
        YyAtIGh0dHA6Ly94MjY1Lm9yZyAtIG9wdGlvbnM6IGNwdWlkPTM0IGZyYW1lLXRocmVhZHM9MSBuby13cHAgbm8tcG1vZGUgbm8t
        cG1lIG5vLXBzbnIgbm8tc3NpbSBsb2ctbGV2ZWw9MCBiaXRkZXB0aD0xMCBpbnB1dC1jc3A9MSBmcHM9NTAvMSBpbnB1dC1yZXM9
        NjR4NjQgaW50ZXJsYWNlPTAgdG90YWwtZnJhbWVzPTAgbGV2ZWwtaWRjPTAgaGlnaC10aWVyPTEgdWhkLWJkPTAgcmVmPTEgbm8t
        YWxsb3ctbm9uLWNvbmZvcm1hbmNlIG5vLXJlcGVhdC1oZWFkZXJzIGFubmV4YiBuby1hdWQgbm8tZW9iIG5vLWVvcyBuby1ocmQg
        aW5mbyBoYXNoPTAgdGVtcG9yYWwtbGF5ZXJzPTAgb3Blbi1nb3AgbWluLWtleWludD0zMCBrZXlpbnQ9MzAgZ29wLWxvb2thaGVh
        ZD0wIGJmcmFtZXM9NCBiLWFkYXB0PTAgYi1weXJhbWlkIGJmcmFtZS1iaWFzPTAgcmMtbG9va2FoZWFkPTUgbG9va2FoZWFkLXNs
        aWNlcz0wIHNjZW5lY3V0PTAgbm8taGlzdC1zY2VuZWN1dCByYWRsPTAgbm8tc3BsaWNlIG5vLWludHJhLXJlZnJlc2ggY3R1PTMy
        IG1pbi1jdS1zaXplPTE2IG5vLXJlY3Qgbm8tYW1wIG1heC10dS1zaXplPTMyIHR1LWludGVyLWRlcHRoPTEgdHUtaW50cmEtZGVw
        dGg9MSBsaW1pdC10dT0wIHJkb3EtbGV2ZWw9MCBkeW5hbWljLXJkPTAuMDAgbm8tc3NpbS1yZCBuby1zaWduaGlkZSBuby10c2tp
        cCBuci1pbnRyYT0wIG5yLWludGVyPTAgbm8tY29uc3RyYWluZWQtaW50cmEgc3Ryb25nLWludHJhLXNtb290aGluZyBtYXgtbWVy
        Z2U9MiBsaW1pdC1yZWZzPTAgbm8tbGltaXQtbW9kZXMgbWU9MCBzdWJtZT0wIG1lcmFuZ2U9NTcgdGVtcG9yYWwtbXZwIG5vLWZy
        YW1lLWR1cCBuby1obWUgbm8td2VpZ2h0cCBuby13ZWlnaHRiIG5vLWFuYWx5emUtc3JjLXBpY3MgZGVibG9jaz0wOjAgbm8tc2Fv
        IG5vLXNhby1ub24tZGVibG9jayByZD0yIHNlbGVjdGl2ZS1zYW89MCBlYXJseS1za2lwIHJza2lwIGZhc3QtaW50cmEgbm8tdHNr
        aXAtZmFzdCBuby1jdS1sb3NzbGVzcyBuby1iLWludHJhIG5vLXNwbGl0cmQtc2tpcCByZHBlbmFsdHk9MCBwc3ktcmQ9Mi4wMCBw
        c3ktcmRvcT0wLjAwIG5vLXJkLXJlZmluZSBuby1sb3NzbGVzcyBjYnFwb2Zmcz0wIGNycXBvZmZzPTAgcmM9Y3JmIGNyZj0yOC4w
        IHFjb21wPTAuNjAgcXBzdGVwPTQgc3RhdHMtd3JpdGU9MCBzdGF0cy1yZWFkPTAgaXByYXRpbz0xLjQwIHBicmF0aW89MS4zMCBh
        cS1tb2RlPTEgYXEtc3RyZW5ndGg9MC4wMCBjdXRyZWUgem9uZS1jb3VudD0wIG5vLXN0cmljdC1jYnIgcWctc2l6ZT0zMiBuby1y
        Yy1ncmFpbiBxcG1heD02OSBxcG1pbj0wIG5vLWNvbnN0LXZidiBzYXI9MSBvdmVyc2Nhbj0wIHZpZGVvZm9ybWF0PTUgcmFuZ2U9
        MCBjb2xvcnByaW09MiB0cmFuc2Zlcj0yIGNvbG9ybWF0cml4PTIgY2hyb21hbG9jPTAgZGlzcGxheS13aW5kb3c9MCBjbGw9MCww
        IG1pbi1sdW1hPTAgbWF4LWx1bWE9MTAyMyBsb2cyLW1heC1wb2MtbHNiPTggdnVpLXRpbWluZy1pbmZvIHZ1aS1ocmQtaW5mbyBz
        bGljZXM9MSBuby1vcHQtcXAtcHBzIG5vLW9wdC1yZWYtbGlzdC1sZW5ndGgtcHBzIG5vLW11bHRpLXBhc3Mtb3B0LXJwcyBzY2Vu
        ZWN1dC1iaWFzPTAuMDUgbm8tb3B0LWN1LWRlbHRhLXFwIG5vLWFxLW1vdGlvbiBuby1oZHIxMCBuby1oZHIxMC1vcHQgbm8tZGhk
        cjEwLW9wdCBuby1pZHItcmVjb3Zlcnktc2VpIGFuYWx5c2lzLXJldXNlLWxldmVsPTAgYW5hbHlzaXMtc2F2ZS1yZXVzZS1sZXZl
        bD0wIGFuYWx5c2lzLWxvYWQtcmV1c2UtbGV2ZWw9MCBzY2FsZS1mYWN0b3I9MCByZWZpbmUtaW50cmE9MCByZWZpbmUtaW50ZXI9
        MCByZWZpbmUtbXY9MSByZWZpbmUtY3R1LWRpc3RvcnRpb249MCBuby1saW1pdC1zYW8gY3R1LWluZm89MCBuby1sb3dwYXNzLWRj
        dCByZWZpbmUtYW5hbHlzaXMtdHlwZT0wIGNvcHktcGljPTEgbWF4LWF1c2l6ZS1mYWN0b3I9MS4wIG5vLWR5bmFtaWMtcmVmaW5l
        IG5vLXNpbmdsZS1zZWkgbm8taGV2Yy1hcSBuby1zdnQgbm8tZmllbGQgcXAtYWRhcHRhdGlvbi1yYW5nZT0xLjAwIHNjZW5lY3V0
        LWF3YXJlLXFwPTBjb25mb3JtYW5jZS13aW5kb3ctb2Zmc2V0cyByaWdodD0wIGJvdHRvbT0wIGRlY29kZXItbWF4LXJhdGU9MCBu
        by12YnYtbGl2ZS1tdWx0aS1wYXNzIG5vLW1jc3RmIG5vLXNicmMgbm8tZnJhbWUtcmOAAAAACmZpZWwBAAAAABBwYXNwAAAAAQAA
        AAEAAAAUYnRydAAAAAAAAE6eAAAAAAAAABhzdHRzAAAAAAAAAAEAAAA8AAABAAAAABhzdHNzAAAAAAAAAAIAAAABAAAAGwAAAEhz
        ZHRwAAAAACAQEBgYGBAQGBgYEBAYGBgQEBgYGBAQGBgYIBAYGBgQEBgYGBAQGBgYEBAYGBgQEBgYGBAQGBgYEBAYGAAAAZhjdHRz
        AAAAAAAAADEAAAABAAACAAAAAAEAAAYAAAAAAQAAAwAAAAACAAAAAAAAAAEAAAEAAAAAAQAABgAAAAABAAADAAAAAAIAAAAAAAAA
        AQAAAQAAAAABAAAGAAAAAAEAAAMAAAAAAgAAAAAAAAABAAABAAAAAAEAAAYAAAAAAQAAAwAAAAACAAAAAAAAAAEAAAEAAAAAAQAA
        BgAAAAABAAADAAAAAAIAAAAAAAAAAQAAAQAAAAABAAAGAAAAAAEAAAMAAAAAAgAAAAAAAAABAAABAAAAAAEAAAYAAAAAAQAAAwAA
        AAACAAAAAAAAAAEAAAEAAAAAAQAABgAAAAABAAADAAAAAAIAAAAAAAAAAQAAAQAAAAABAAAGAAAAAAEAAAMAAAAAAgAAAAAAAAAB
        AAABAAAAAAEAAAYAAAAAAQAAAwAAAAACAAAAAAAAAAEAAAEAAAAAAQAABgAAAAABAAADAAAAAAIAAAAAAAAAAQAAAQAAAAABAAAF
        AAAAAAEAAAIAAAAAAQAAAAAAAAABAAABAAAAABxzdHNjAAAAAAAAAAEAAAABAAAAPAAAAAEAAAEEc3RzegAAAAAAAAAAAAAAPAAA
        BBUAAAAVAAAADgAAAA8AAAAPAAAADgAAACwAAAAPAAAAEAAAABAAAAAPAAAALAAAABAAAAAQAAAAEAAAAA8AAAA6AAAAEAAAABAA
        AAAQAAAADwAAAC4AAAAQAAAAEAAAABAAAAAPAAADAwAAABAAAAAQAAAAEAAAAA8AAAAZAAAADgAAAA8AAAAPAAAADgAAAC4AAAAP
        AAAAEAAAABAAAAAPAAAAMAAAABAAAAAQAAAAEAAAAA8AAAA1AAAAEAAAABAAAAAQAAAADwAAACwAAAAQAAAAEAAAABAAAAAPAAAA
        LwAAABAAAAAPAAAADwAAABRzdGNvAAAAAAAAAAEAAA+EAAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFw
        cGwAAAAAAAAAAAAAAAAtaWxzdAAAACWpdG9vAAAAHWRhdGEAAAABAAAAAExhdmY2Mi4xMi4xMDEAAAAIZnJlZQAAC9NtZGF0AAAE
        ESgBrCmAqAtj3ixvvtxkKmMD3eX+ImIdIq0/LQeyKklx7fWmEt6THfOXuqnxTy5j68zrVuZCkBZyAW3NTMnVjDWR58jaXrdK4MTV
        4zZD4kgnUXLTiZjW6GVzt8f/1mmD9wKt8fsbkIZldLLRz2XXJreSW52v0Hs30w1FCqCcD0vuQ5liavcsOoD3gsstUZYvgeFGsWtL
        bFSkSDeWJ7BcAiN/z9yxYVkNWrpWVYkKE/+JabKF0F11CrKkNRv45k/fLEamFfTqAI5vBqQVIqE5o925E14g4ZQF+nWtk1qaMRWT
        qnDREz035U3J2USY03KgMr2qGDDxxTMsFw6tOV+ipcPuS1AtJvyEaNS6cABF+nUKnegDInOgCmVCPWZ5u75iUFCZTzEwVncVIlXZ
        eRYVLfgLpMWt2RfKQEFuapdJSWuwwjb8LamSib4jum3wDfrVdM2j0bJAnnZvDO6Iy3yaeP26GhKv///ba5Q48eqAjXtiPE4j2Pwo
        A+qlwxf9TbPz479o2DJDzfm7kSBtTxJVt+yoyuVS0iPHwUvyMDZn1szJSSHzD6EJt8zAaLmgCQnlDmB0xPcZdikT8DnLOkwnEltF
        QkIXnxUpaJgcASICN1J0EM9R8lVZjK+rTElRT3tsykgs7QSpDt7Mf0S5PPEgNHUwmMMHn6Gs2k1zpXQRD60DtcgMWfoqprALJcjZ
        onISd/e6G+pVlY+ByiKB+XTN4QPK64Tqk0ObanoRNqWoz3lZ62JcZpR/NYLaYvTE+mwNemnifXmNoHT9wPkC6zyzE4B7IKmt5Oq5
        DjqcqxdeUrMFvSTc3q2TgkaX6sOQF6estWisjYbGFCbA38FpEURoFpQuc8wdY8uYDhbjCCDNOxMOnijsFNrXpYhUs3ZNTAx13AMC
        Phd72hbDRGCZpO80Z4fO937bk4WUMdvK8JZrn+PgG/Kr+mprjHf7AvP88YXxdFGwkEhDTYHg8wmVU4/AfE9AWVKChz5//ynZsaMo
        pC23dnt7BCckf9BzoZDmZxCsyyKn5XCjddEl+W4I/UO2rdWQjjIUOQM0vhfoi2+KrC0CUHiAKZ3ag9x+y5cNeHN09L2S9XAALIkr
        OchQrgsB2AvE/AO1nQa0DOwLPAaQWYEgJV5yTe08S371798MB1SrF2jU88SIleLNF7cob3v01E+ibmbQGTCd3FsV7CZbspvs9XOq
        aAUf2jJ1ksoU7qji2v+b1OON7e2ODMFaXuoAcqZoF/bgiZggZJnvHretRW6ZGfjIHOAECVXpwXHuW/MgEFh1necwZOM0bti9FSvb
        7kru2YB2KOdVMc8DEAjSUO2vdmU4ShS8g5hU+YKnpbWHyI5Gt7hyQ8bo1xrHMBT00EY+Cyn8hUbj8t8QkrEvGDGJvgAAABECAdAp
        S4gUQLNaRKOrvmUrlwAAAAoCAeBknWCBZJJ4AAAACwAB4CT1XokDGJDwAAAACwAB4ETXXokDCJDwAAAACgAB4Ia34IGMkPAAAAAo
        AgHQUJLV4gUQs1pBXstflTAR3T1JbAVIbopYqDUPYTj4IWE81h/fcAAAAAsCAeECJ1dYIFmSeAAAAAwAAeDG9VXokDGAkPAAAAAM
        AAHg5tV16JAwgJDwAAAACwAB4SIt14IGMJDwAAAAKAIB0Hiy1dYgUbNX3UUiza+6i4MPZOqs+PtC41JPtDUUci+9EDsBEIAAAAAM
        AgHhoidS1ggWQJJ4AAAADAAB4Wb1VeiQMYCQ8AAAAAwAAeGG1XXokDCAkPAAAAALAAHhwi3XggYwkPAAAAA2AgHQoLLV1iBRs1pF
        8J9CPc4R37vjlJUMsDOIYRTv0YJs83cr9E8qQK09NOxkCdS4zy+1btkwAAAADAIB4kInUtYIFsCSeAAAAAwAAeIG9VXokDCAkPAA
        AAAMAAHiJtV16JAxgJDwAAAACwAB4mIt14IGMJDwAAAAKgIB0Miy1dYgU7NaRdlMD+s+HomYswol7sg/lZAGfD5iKIaClD9WuaxS
        2AAAAAwCAeLiJ1LWCBZAkngAAAAMAAHipvVV6JAwgJDwAAAADAAB4sbVdeiQMYCQ8AAAAAsAAeMCLdeCBjCQ8AAAAv8qAax4WUjJ
        CWCjD2eNFYBL9VgaG1nDmWYZT44HnoNrRoPGSdWf2Hq+kAVp0AETi8bXaTSzsF+JUlDhD3/F6v4RJdJ0nr//gzctK9Kf0HYjnaTZ
        QMpnbQiyS3n232faVg21N8KsG1ZNqscyqiiIt+wc12DDVvXwz86qXsby+oe0oXOGHLAA6ze7alSy/+qrwwd7NVYDo6yNBZR23bKp
        M5r65RAYpV46uGId2xk+8hFx+DOKF9516y9z2Sc00Ri24Iq8OdCVWNvHWKPB635A0pBuAawUdfGgyCjIPQh1+ZsBXLhT41eJcSlV
        UWuNOqZIyerG7zNStDP2dylZqCW9Ul3XmIVPSEc2f//1fOq+gXwDQffb0/SFIXZLPKzHdWYD8RUI1pDR0l5ExhcvZ/zMdpZ4t8Rb
        3QIVCbN0yjPy1vJ4jjIoHM1NcKMLIDnBVOh+zt3QM3leO+4ZFjjf8r6ocDE3KoN2gNvpPm5L7CIhQ2ifdpvoTgBmjVh6cTm/Wf49
        1E5/q/5y8gPCFZxtlbEBQZkn2j7DPTns4UYiJ1uD4UzOKIMq4i+rfpo8hTFNA8HtVN5lJ6Tv0c9CPeh5uAdwwKVrbaPtiazzMXZ8
        jOAfZ6hngSyJI4nhYaAOHW/sy5dm1McbDzOwuZ1T0nPhGqyWqtEvQ69uxZZZNkWS55TB8snliUp4sKy1/uLfA8tGJUBuumU7yJbO
        xPgOpaR06JWocWRaho4OonanCAUCSTLLif+PF4HqU6crLSctC7oafi+qctoINabIeRpCshIeTFlTDX7bdZIBUWd74n7FdxIpmLzt
        JCcvZyMLQNpn1zHi6WV4IBFALtCCOBSJ2P/TcS9/Z0C/BRexcGZFe88yAbVa+15bZQ44+t92JW+PlM3cDHMdP+cGWxf7QdajToUs
        mR17uo1Y6BteMHVLrjVz37Mu4OZtaIqp1LwfD/Gl0BAF8ph1b9l6rYoUppu2nj1CrHd/+0kJgooDopxHesfYiVHVpsapV0t6aHAr
        jyCdhMCBL/e4CAAAAAwSAeOCJ1LWCBbAkngAAAAMEAHjRvVV6JAxgJDwAAAADBAB42bVdeiQMYCQ8AAAAAsQAeOiLdeCBhCQ8AAA
        ABUCAdEZS4gUwKWUARtgIeLbo2Dsm4AAAAAKAgHkJJ1ggWSSeAAAAAsAAePk9V6JAxiQ8AAAAAsAAeQE116JAxiQ8AAAAAoAAeRG
        t+CBhJDwAAAAKgIB0UCS1eIFMLNaRZJaHzbJq9zDac6CVeR4Ose49AXhreJ5h3CAkxnAgAAAAAsCAeTCJ1dYIFmSeAAAAAwAAeSG
        9VXokDCAkPAAAAAMAAHkptV16JAxgJDwAAAACwAB5OIt14IGEJDwAAAALAIB0Wiy1dYgU7NX0oxEpyVXkd0PlmoD4UCzwOy1Kn4H
        M30P7lZDezVWpePWAAAADAIB5WInUtYIFkCSeAAAAAwAAeUm9VXokDCAkPAAAAAMAAHlRtV16JAxgJDwAAAACwAB5YIt14IGEJDw
        AAAAMQIB0ZCy1dYgU7NaQVA7FgvGoiPkdZiJRmkpLH4HCwR/7s/PnTGo0asEbqN5ii4n+OAAAAAMAgHmAidS1ggWwJJ4AAAADAAB
        5cb1VeiQMICQ8AAAAAwAAeXm1XXokDCAkPAAAAALAAHmIi3XggYwkPAAAAAoAgHRuLLV1iBTs1pIU6hYy2wO0STGAgb99r9Labtc
        ybfbnmQ6/OsmvgAAAAwCAeaiJ1LWCBbAkngAAAAMAAHmZvVV6JAwgJDwAAAADAAB5obVdeiQMICQ8AAAAAsAAebCLdeCBhCQ8AAA
        ACsCAdHYslXWIFOtmAzX0NRed3pQXw+62wWHkLbUGOmJJygg3cAOzHxoBHGAAAAADAIB5yIlUtYIFsCSeAAAAAsAAecG9deiQMaQ
        8AAAAAsAAedCLVeCBjCQ8A==
        """

    private static let missingFixtureBase64 = """
        AAAAHGZ0eXBpc29tAAACAGlzb21pc28ybXA0MQAADcBtb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAAEiAABAAABAAAAAAAA
        AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAM6nRy
        YWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAEAAAAAAAAEiAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA
        AAAAAAAAAEAAAAAAQAAAAEAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAABIgAAAIAAAEAAAAADGJtZGlhAAAAIG1kaGQAAAAA
        AAAAAAAAAAAAADIAAAA8AFXEAAAAAAAtaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAAAAwNbWluZgAA
        ABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAALzXN0YmwAAAoZc3RzZAAAAAAA
        AAABAAAKCWh2YzEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAQABAAEgAAABIAAAAAAAAAAEVTGF2YzYyLjI4LjEwMSBsaWJ4MjY1
        AAAAAAAAAAAAAAAY//8AAAmFaHZjQwECIAAAAJAAAAAAAB7wAPz9+voAAA8EoAABABhAAQwB//8CIAAAAwCQAAADAAADAB6VmAmh
        AAEAKkIBAQIgAAADAJAAAAMAAAMAHqAggQTZZWZKTC8BaAgAAAMACAAAAwGQQKIAAQAGRAHAc8CJJwABCQpOAQX///////////8F
        LKLeCbUXR9u7VaT+f8L8TngyNjUgKGJ1aWxkIDIxNikgLSA0LjIrMS1lNDQ0NzQ0OltNYWMgT1MgWF1bY2xhbmcgMjEuMC4wXVs2
        NCBiaXRdIDEwYml0IC0gSC4yNjUvSEVWQyBjb2RlYyAtIENvcHlyaWdodCAyMDEzLTIwMTggKGMpIE11bHRpY29yZXdhcmUsIElu
        YyAtIGh0dHA6Ly94MjY1Lm9yZyAtIG9wdGlvbnM6IGNwdWlkPTM0IGZyYW1lLXRocmVhZHM9MSBuby13cHAgbm8tcG1vZGUgbm8t
        cG1lIG5vLXBzbnIgbm8tc3NpbSBsb2ctbGV2ZWw9MCBiaXRkZXB0aD0xMCBpbnB1dC1jc3A9MSBmcHM9NTAvMSBpbnB1dC1yZXM9
        NjR4NjQgaW50ZXJsYWNlPTAgdG90YWwtZnJhbWVzPTAgbGV2ZWwtaWRjPTAgaGlnaC10aWVyPTEgdWhkLWJkPTAgcmVmPTEgbm8t
        YWxsb3ctbm9uLWNvbmZvcm1hbmNlIG5vLXJlcGVhdC1oZWFkZXJzIGFubmV4YiBuby1hdWQgbm8tZW9iIG5vLWVvcyBuby1ocmQg
        aW5mbyBoYXNoPTAgdGVtcG9yYWwtbGF5ZXJzPTAgb3Blbi1nb3AgbWluLWtleWludD0zMCBrZXlpbnQ9MzAgZ29wLWxvb2thaGVh
        ZD0wIGJmcmFtZXM9NCBiLWFkYXB0PTAgYi1weXJhbWlkIGJmcmFtZS1iaWFzPTAgcmMtbG9va2FoZWFkPTUgbG9va2FoZWFkLXNs
        aWNlcz0wIHNjZW5lY3V0PTAgbm8taGlzdC1zY2VuZWN1dCByYWRsPTAgbm8tc3BsaWNlIG5vLWludHJhLXJlZnJlc2ggY3R1PTMy
        IG1pbi1jdS1zaXplPTE2IG5vLXJlY3Qgbm8tYW1wIG1heC10dS1zaXplPTMyIHR1LWludGVyLWRlcHRoPTEgdHUtaW50cmEtZGVw
        dGg9MSBsaW1pdC10dT0wIHJkb3EtbGV2ZWw9MCBkeW5hbWljLXJkPTAuMDAgbm8tc3NpbS1yZCBuby1zaWduaGlkZSBuby10c2tp
        cCBuci1pbnRyYT0wIG5yLWludGVyPTAgbm8tY29uc3RyYWluZWQtaW50cmEgc3Ryb25nLWludHJhLXNtb290aGluZyBtYXgtbWVy
        Z2U9MiBsaW1pdC1yZWZzPTAgbm8tbGltaXQtbW9kZXMgbWU9MCBzdWJtZT0wIG1lcmFuZ2U9NTcgdGVtcG9yYWwtbXZwIG5vLWZy
        YW1lLWR1cCBuby1obWUgbm8td2VpZ2h0cCBuby13ZWlnaHRiIG5vLWFuYWx5emUtc3JjLXBpY3MgZGVibG9jaz0wOjAgbm8tc2Fv
        IG5vLXNhby1ub24tZGVibG9jayByZD0yIHNlbGVjdGl2ZS1zYW89MCBlYXJseS1za2lwIHJza2lwIGZhc3QtaW50cmEgbm8tdHNr
        aXAtZmFzdCBuby1jdS1sb3NzbGVzcyBuby1iLWludHJhIG5vLXNwbGl0cmQtc2tpcCByZHBlbmFsdHk9MCBwc3ktcmQ9Mi4wMCBw
        c3ktcmRvcT0wLjAwIG5vLXJkLXJlZmluZSBuby1sb3NzbGVzcyBjYnFwb2Zmcz0wIGNycXBvZmZzPTAgcmM9Y3JmIGNyZj0yOC4w
        IHFjb21wPTAuNjAgcXBzdGVwPTQgc3RhdHMtd3JpdGU9MCBzdGF0cy1yZWFkPTAgaXByYXRpbz0xLjQwIHBicmF0aW89MS4zMCBh
        cS1tb2RlPTEgYXEtc3RyZW5ndGg9MC4wMCBjdXRyZWUgem9uZS1jb3VudD0wIG5vLXN0cmljdC1jYnIgcWctc2l6ZT0zMiBuby1y
        Yy1ncmFpbiBxcG1heD02OSBxcG1pbj0wIG5vLWNvbnN0LXZidiBzYXI9MSBvdmVyc2Nhbj0wIHZpZGVvZm9ybWF0PTUgcmFuZ2U9
        MCBjb2xvcnByaW09MiB0cmFuc2Zlcj0yIGNvbG9ybWF0cml4PTIgY2hyb21hbG9jPTAgZGlzcGxheS13aW5kb3c9MCBjbGw9MCww
        IG1pbi1sdW1hPTAgbWF4LWx1bWE9MTAyMyBsb2cyLW1heC1wb2MtbHNiPTggdnVpLXRpbWluZy1pbmZvIHZ1aS1ocmQtaW5mbyBz
        bGljZXM9MSBuby1vcHQtcXAtcHBzIG5vLW9wdC1yZWYtbGlzdC1sZW5ndGgtcHBzIG5vLW11bHRpLXBhc3Mtb3B0LXJwcyBzY2Vu
        ZWN1dC1iaWFzPTAuMDUgbm8tb3B0LWN1LWRlbHRhLXFwIG5vLWFxLW1vdGlvbiBuby1oZHIxMCBuby1oZHIxMC1vcHQgbm8tZGhk
        cjEwLW9wdCBuby1pZHItcmVjb3Zlcnktc2VpIGFuYWx5c2lzLXJldXNlLWxldmVsPTAgYW5hbHlzaXMtc2F2ZS1yZXVzZS1sZXZl
        bD0wIGFuYWx5c2lzLWxvYWQtcmV1c2UtbGV2ZWw9MCBzY2FsZS1mYWN0b3I9MCByZWZpbmUtaW50cmE9MCByZWZpbmUtaW50ZXI9
        MCByZWZpbmUtbXY9MSByZWZpbmUtY3R1LWRpc3RvcnRpb249MCBuby1saW1pdC1zYW8gY3R1LWluZm89MCBuby1sb3dwYXNzLWRj
        dCByZWZpbmUtYW5hbHlzaXMtdHlwZT0wIGNvcHktcGljPTEgbWF4LWF1c2l6ZS1mYWN0b3I9MS4wIG5vLWR5bmFtaWMtcmVmaW5l
        IG5vLXNpbmdsZS1zZWkgbm8taGV2Yy1hcSBuby1zdnQgbm8tZmllbGQgcXAtYWRhcHRhdGlvbi1yYW5nZT0xLjAwIHNjZW5lY3V0
        LWF3YXJlLXFwPTBjb25mb3JtYW5jZS13aW5kb3ctb2Zmc2V0cyByaWdodD0wIGJvdHRvbT0wIGRlY29kZXItbWF4LXJhdGU9MCBu
        by12YnYtbGl2ZS1tdWx0aS1wYXNzIG5vLW1jc3RmIG5vLXNicmMgbm8tZnJhbWUtcmOAAAAACmZpZWwBAAAAABBwYXNwAAAAAQAA
        AAEAAAAUYnRydAAAAAAAAE6eAABOngAAABhzdHRzAAAAAAAAAAEAAAA8AAABAAAAABhzdHNzAAAAAAAAAAIAAAABAAAAGwAAAEhz
        ZHRwAAAAACAQEBgYGBAQGBgYEBAYGBgQEBgYGBAQGBgYIBAYGBgQEBgYGBAQGBgYEBAYGBgQEBgYGBAQGBgYEBAYGAAAABxzdHNj
        AAAAAAAAAAEAAAABAAAAPAAAAAEAAAEEc3RzegAAAAAAAAAAAAAAPAAABBUAAAAVAAAADgAAAA8AAAAPAAAADgAAACwAAAAPAAAA
        EAAAABAAAAAPAAAALAAAABAAAAAQAAAAEAAAAA8AAAA6AAAAEAAAABAAAAAQAAAADwAAAC4AAAAQAAAAEAAAABAAAAAPAAADAwAA
        ABAAAAAQAAAAEAAAAA8AAAAZAAAADgAAAA8AAAAPAAAADgAAAC4AAAAPAAAAEAAAABAAAAAPAAAAMAAAABAAAAAQAAAAEAAAAA8A
        AAA1AAAAEAAAABAAAAAQAAAADwAAACwAAAAQAAAAEAAAABAAAAAPAAAALwAAABAAAAAPAAAADwAAABRzdGNvAAAAAAAAAAEAAA3s
        AAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAtaWxzdAAAACWpdG9vAAAAHWRh
        dGEAAAABAAAAAExhdmY2Mi4xMi4xMDEAAAAIZnJlZQAAC9NtZGF0AAAEESgBrCmAqAtj3ixvvtxkKmMD3eX+ImIdIq0/LQeyKklx
        7fWmEt6THfOXuqnxTy5j68zrVuZCkBZyAW3NTMnVjDWR58jaXrdK4MTV4zZD4kgnUXLTiZjW6GVzt8f/1mmD9wKt8fsbkIZldLLR
        z2XXJreSW52v0Hs30w1FCqCcD0vuQ5liavcsOoD3gsstUZYvgeFGsWtLbFSkSDeWJ7BcAiN/z9yxYVkNWrpWVYkKE/+JabKF0F11
        CrKkNRv45k/fLEamFfTqAI5vBqQVIqE5o925E14g4ZQF+nWtk1qaMRWTqnDREz035U3J2USY03KgMr2qGDDxxTMsFw6tOV+ipcPu
        S1AtJvyEaNS6cABF+nUKnegDInOgCmVCPWZ5u75iUFCZTzEwVncVIlXZeRYVLfgLpMWt2RfKQEFuapdJSWuwwjb8LamSib4jum3w
        DfrVdM2j0bJAnnZvDO6Iy3yaeP26GhKv///ba5Q48eqAjXtiPE4j2PwoA+qlwxf9TbPz479o2DJDzfm7kSBtTxJVt+yoyuVS0iPH
        wUvyMDZn1szJSSHzD6EJt8zAaLmgCQnlDmB0xPcZdikT8DnLOkwnEltFQkIXnxUpaJgcASICN1J0EM9R8lVZjK+rTElRT3tsykgs
        7QSpDt7Mf0S5PPEgNHUwmMMHn6Gs2k1zpXQRD60DtcgMWfoqprALJcjZonISd/e6G+pVlY+ByiKB+XTN4QPK64Tqk0ObanoRNqWo
        z3lZ62JcZpR/NYLaYvTE+mwNemnifXmNoHT9wPkC6zyzE4B7IKmt5Oq5DjqcqxdeUrMFvSTc3q2TgkaX6sOQF6estWisjYbGFCbA
        38FpEURoFpQuc8wdY8uYDhbjCCDNOxMOnijsFNrXpYhUs3ZNTAx13AMCPhd72hbDRGCZpO80Z4fO937bk4WUMdvK8JZrn+PgG/Kr
        +mprjHf7AvP88YXxdFGwkEhDTYHg8wmVU4/AfE9AWVKChz5//ynZsaMopC23dnt7BCckf9BzoZDmZxCsyyKn5XCjddEl+W4I/UO2
        rdWQjjIUOQM0vhfoi2+KrC0CUHiAKZ3ag9x+y5cNeHN09L2S9XAALIkrOchQrgsB2AvE/AO1nQa0DOwLPAaQWYEgJV5yTe08S371
        798MB1SrF2jU88SIleLNF7cob3v01E+ibmbQGTCd3FsV7CZbspvs9XOqaAUf2jJ1ksoU7qji2v+b1OON7e2ODMFaXuoAcqZoF/bg
        iZggZJnvHretRW6ZGfjIHOAECVXpwXHuW/MgEFh1necwZOM0bti9FSvb7kru2YB2KOdVMc8DEAjSUO2vdmU4ShS8g5hU+YKnpbWH
        yI5Gt7hyQ8bo1xrHMBT00EY+Cyn8hUbj8t8QkrEvGDGJvgAAABECAdApS4gUQLNaRKOrvmUrlwAAAAoCAeBknWCBZJJ4AAAACwAB
        4CT1XokDGJDwAAAACwAB4ETXXokDCJDwAAAACgAB4Ia34IGMkPAAAAAoAgHQUJLV4gUQs1pBXstflTAR3T1JbAVIbopYqDUPYTj4
        IWE81h/fcAAAAAsCAeECJ1dYIFmSeAAAAAwAAeDG9VXokDGAkPAAAAAMAAHg5tV16JAwgJDwAAAACwAB4SIt14IGMJDwAAAAKAIB
        0Hiy1dYgUbNX3UUiza+6i4MPZOqs+PtC41JPtDUUci+9EDsBEIAAAAAMAgHhoidS1ggWQJJ4AAAADAAB4Wb1VeiQMYCQ8AAAAAwA
        AeGG1XXokDCAkPAAAAALAAHhwi3XggYwkPAAAAA2AgHQoLLV1iBRs1pF8J9CPc4R37vjlJUMsDOIYRTv0YJs83cr9E8qQK09NOxk
        CdS4zy+1btkwAAAADAIB4kInUtYIFsCSeAAAAAwAAeIG9VXokDCAkPAAAAAMAAHiJtV16JAxgJDwAAAACwAB4mIt14IGMJDwAAAA
        KgIB0Miy1dYgU7NaRdlMD+s+HomYswol7sg/lZAGfD5iKIaClD9WuaxS2AAAAAwCAeLiJ1LWCBZAkngAAAAMAAHipvVV6JAwgJDw
        AAAADAAB4sbVdeiQMYCQ8AAAAAsAAeMCLdeCBjCQ8AAAAv8qAax4WUjJCWCjD2eNFYBL9VgaG1nDmWYZT44HnoNrRoPGSdWf2Hq+
        kAVp0AETi8bXaTSzsF+JUlDhD3/F6v4RJdJ0nr//gzctK9Kf0HYjnaTZQMpnbQiyS3n232faVg21N8KsG1ZNqscyqiiIt+wc12DD
        VvXwz86qXsby+oe0oXOGHLAA6ze7alSy/+qrwwd7NVYDo6yNBZR23bKpM5r65RAYpV46uGId2xk+8hFx+DOKF9516y9z2Sc00Ri2
        4Iq8OdCVWNvHWKPB635A0pBuAawUdfGgyCjIPQh1+ZsBXLhT41eJcSlVUWuNOqZIyerG7zNStDP2dylZqCW9Ul3XmIVPSEc2f//1
        fOq+gXwDQffb0/SFIXZLPKzHdWYD8RUI1pDR0l5ExhcvZ/zMdpZ4t8Rb3QIVCbN0yjPy1vJ4jjIoHM1NcKMLIDnBVOh+zt3QM3le
        O+4ZFjjf8r6ocDE3KoN2gNvpPm5L7CIhQ2ifdpvoTgBmjVh6cTm/Wf491E5/q/5y8gPCFZxtlbEBQZkn2j7DPTns4UYiJ1uD4UzO
        KIMq4i+rfpo8hTFNA8HtVN5lJ6Tv0c9CPeh5uAdwwKVrbaPtiazzMXZ8jOAfZ6hngSyJI4nhYaAOHW/sy5dm1McbDzOwuZ1T0nPh
        GqyWqtEvQ69uxZZZNkWS55TB8snliUp4sKy1/uLfA8tGJUBuumU7yJbOxPgOpaR06JWocWRaho4OonanCAUCSTLLif+PF4HqU6cr
        LSctC7oafi+qctoINabIeRpCshIeTFlTDX7bdZIBUWd74n7FdxIpmLztJCcvZyMLQNpn1zHi6WV4IBFALtCCOBSJ2P/TcS9/Z0C/
        BRexcGZFe88yAbVa+15bZQ44+t92JW+PlM3cDHMdP+cGWxf7QdajToUsmR17uo1Y6BteMHVLrjVz37Mu4OZtaIqp1LwfD/Gl0BAF
        8ph1b9l6rYoUppu2nj1CrHd/+0kJgooDopxHesfYiVHVpsapV0t6aHArjyCdhMCBL/e4CAAAAAwSAeOCJ1LWCBbAkngAAAAMEAHj
        RvVV6JAxgJDwAAAADBAB42bVdeiQMYCQ8AAAAAsQAeOiLdeCBhCQ8AAAABUCAdEZS4gUwKWUARtgIeLbo2Dsm4AAAAAKAgHkJJ1g
        gWSSeAAAAAsAAePk9V6JAxiQ8AAAAAsAAeQE116JAxiQ8AAAAAoAAeRGt+CBhJDwAAAAKgIB0UCS1eIFMLNaRZJaHzbJq9zDac6C
        VeR4Ose49AXhreJ5h3CAkxnAgAAAAAsCAeTCJ1dYIFmSeAAAAAwAAeSG9VXokDCAkPAAAAAMAAHkptV16JAxgJDwAAAACwAB5OIt
        14IGEJDwAAAALAIB0Wiy1dYgU7NX0oxEpyVXkd0PlmoD4UCzwOy1Kn4HM30P7lZDezVWpePWAAAADAIB5WInUtYIFkCSeAAAAAwA
        AeUm9VXokDCAkPAAAAAMAAHlRtV16JAxgJDwAAAACwAB5YIt14IGEJDwAAAAMQIB0ZCy1dYgU7NaQVA7FgvGoiPkdZiJRmkpLH4H
        CwR/7s/PnTGo0asEbqN5ii4n+OAAAAAMAgHmAidS1ggWwJJ4AAAADAAB5cb1VeiQMICQ8AAAAAwAAeXm1XXokDCAkPAAAAALAAHm
        Ii3XggYwkPAAAAAoAgHRuLLV1iBTs1pIU6hYy2wO0STGAgb99r9LabtcybfbnmQ6/OsmvgAAAAwCAeaiJ1LWCBbAkngAAAAMAAHm
        ZvVV6JAwgJDwAAAADAAB5obVdeiQMICQ8AAAAAsAAebCLdeCBhCQ8AAAACsCAdHYslXWIFOtmAzX0NRed3pQXw+62wWHkLbUGOmJ
        Jygg3cAOzHxoBHGAAAAADAIB5yIlUtYIFsCSeAAAAAsAAecG9deiQMaQ8AAAAAsAAedCLVeCBjCQ8A==
        """
}
